### ISSUE TITLE
Hate

### ISSUE THREAD

**Issue by igusfmohican** [wien-subs/Theme#1]
##### Descrieți Problema #####
Adauga la loc acel "triunghi" unde scria ce serie este Bd ca sa se vada mai bine fmm. nu asa http://prntscr.com/i1viql.
bine poate poti si asa. da' adauga inca un lucru ca sa se poata deose mult mai bine 

sa faci o subcategorie. EX 
Anime
     adqwdqw
     asdqwdq
  BD
     asada
     asdaasd

Gasirea dimensiunii imaginilor potrivite pentru aceast aspect al site-ului sa nu para deformate. Recomand sa cautati rezolutia potrivita si daca se poate sa modificati in timp la toate seriile imaginea ( sa fie aceeasi nu conteaza da' sa fie redimensionata)

Alt fundal, vechiul site avea background-ul superb, imagini atent alese.
     daca se poate micsorarea putin a "tab-urilor" /poza: http://prntscr.com/i1vot7 nu cu mult ca sa se 
     poata vedea background-ul daca il bagati

schimbarea culorii din gri intr-una mai vesela, sau chair de sezon, un albastru mai deschis ~ gen sticla, daca ma-ntelegi ar fi super.

bara de meniuri sa aiba mai multe animatii daca se paote 

alegerea imaginilor cu putina atentie sau schimbarea culorii de pe acestea deoarece se poate intampla : 
nu! :   http://prntscr.com/i1vn30 
          http://prntscr.com/i1vn7o
poate : http://prntscr.com/i1vnet

schimbarea pozei de aici http://prntscr.com/i1vo6u

**Comment by fmohican** [comment]
> si cand intri pe site sa aveti niste "postari" fake, cum sunt cele de pe fb, iti canta o melodie intr-un video si dupa , pe la jumatate mare Raget PORNO ce se aude ca sa-ti scoale tot blocul

Ce postări "fake"? fă-mi screenshot. Vreau să văd și eu unde este acel porno.
@igusfmohican

**Comment by igusfmohican** [comment]
was just a prank, bro

**Comment by fmohican** [comment]
@igusfmohican 

poți să detaliezi un pic ideea asta :

> sa faci o subcategorie. EX Anime adqwdqw asdqwdq BD asada asdaasd


Adică ? ce fel de subcategorie? la ce te referi?

**Comment by igusfmohican** [comment]
nu s-au pastrat space-urile , adica ceva gen : http://prntscr.com/i25i8l

**Comment by fmohican** [comment]
Rev. 0.1.7.8 Alpha
