### ISSUE TITLE
^.^

### ISSUE THREAD

**Issue by HandaSei** [wien-subs/Theme#2]
1. Redimensionarea imaginilor de pe panoul mare, cred că asta ar trebui să fie una din prioritățile de top pentru moment, chiar arată foarte nașpa... 👎 /Eventual în loc să apară acolo ultimele episoade care oricum sunt afișate pe prima pagină, ar trebui să fie afișate recomandări de anime-uri random de pe site și poate și anunțuri legate de site etc... :)

2. Tema este foarte bună în general, iar culoarea aia de albastru închis chiar îmi place la nebunie, dar totuși fundalul nu o prea ajută, este mult prea închis și abia se distinge restul site-ului de el, asta în special dacă ai un monitor ca al meu... =)) / Am văzut că cineva a spus că ar fi bine să puneți o imagine (anime) de fundal, dar eu unul chiar nu susțin asta, o culoare simplă ceva mai luminoasă ar fi perfectă, ar păstra tema site-ului curată și mai profesională! :)

3. La search atunci când faci o căutare să nu-ți mai apară toate episoadele separate în rezultat, ci doar pagina principală la seria respectivă, asta chiar ar ajuta! ^.^

**Comment by fmohican** [comment]
1. Avem o soluție care se află pe server-ul de test, în curând o să publicăm noile actualizatori.

2. O să modificăm, ideea este foarte bună cu o culoare solidă de background.

3. Poți să detaliezi un pic ? Nu prea înțeleg la ce te referi.... Cum adică să apară pagina principală de la serie ?

**Comment by HandaSei** [comment]
Deci spre exemplu așa apare acum când cauți un anime ( https://scr.hu/Ae7D4a ), toate episoadele seriei separat, ceea ce poate fi foarte enervant...

La asta m-am referit când am zis pagina principală a seriei ( https://www.wien-subs.ro/anime-parent/rezero-kara-hajimeru-isekai-seikatsu ), deși din ce am văzut nu toate seriile au așa ceva... 

Zic că în loc să apară 100 de episoade la serii mai lungi de exemplu, să apară atunci când cauți doar un link care să te redirecționeze fie pe o pagină de genul ca cea de mai sus, fie spre pagina asta unde văd că episoadele sunt mai ușor de căutat! ( https://www.wien-subs.ro/online/anime-ro-sub/re-zero-kara-hajimeru-isekai-seikatsu )

Exemple:
1. (AnimeHeaven) La fel cum aveți și voi cu redirecționare pe o pagină nouă atunci când faci o căutare! ( https://scr.hu/2a80Kl )
2. (MasterAni) Direct în căsuța de căutare fără alte complicații! ( https://scr.hu/Xz2YYy )

**Comment by fmohican** [comment]
Good. That sound good.
L-am trecut pe listă.

**Comment by fmohican** [comment]
Rezolvat în Versiunea Rev. 0.1.7.8 Alpha

Din păcate search engine-ul este destul de greu de modificat, implică modificări în core-ul wordpress și spun ca momentan nu prea avem timp să ne complicăm chiar în halul acesta, totuși am găsit o alternativă bună la acestă problemă.

**Comment by fmohican** [comment]
@HandaSei Pot închide topic-ul ?

###### *Dacă nu răspunzi în 24h de la momentul postări voi considera ca fiind rezolvat și îl voi închide.*

**Comment by HandaSei** [comment]
Frumos, fundalul care-și schimbă culoarea arată foarte tare! ^.^
Prin alternativă la search cred că te referi la acel folder micuț care acum văd că acum apare lipit de fiecare episod postat și te redirecționează spre seria completă, ceea ce într-adevăr rezolvă o mare parte din problemă! :)

Totuși pentru panoul cu imagini, personal încă cred că ar trebui puse acolo niște recomandări de anime random de pe site și nu ultimele episoade postate care oricum sunt deja pe prima pagină, pur și simplu nu are prea multă logică... =))

**Comment by fmohican** [comment]
Rezolvat în verisunea 0.7.3.1 Alpha.
@HandaSei
